server:
  name: "blog"
  addr: "blog:8082"
grpc:
  name: "blog"
  addr: "blog:8883"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"
zap:
  DebugFileName: "/logs/blog/debug/debug.log"
  InfoFileName:  "/logs/blog/info/info.log"
  WarnFileName:  "/logs/blog/error/error.log"
  MaxSize:       500
  MaxAge:        28
  MaxBackups:    3
redis:
  host: "redis6"
  port: 6379
  password: ""
  db: 0
mysql:
  username: root
  password: root
  host: mysql8
  port: 3306
  db: libra
jwt:
  accessExp: 7
  refreshExp: 30
  accessSecret: libra
  refreshSecret: libra
aliyunoss:
  bucketName: libra-blog
  endpoint: oss-cn-beijing.aliyuncs.com
  roleArn: acs:ram::1297456591392749:role/ramoss
  regin: cn-beijing
  id: LTAI5tB75QwZq1LS3yXJJPk7
  secret: qW1bQq8cTFC2J7ZGLuOKNJfnWU6EfJ