server:
  name: "blog"
  addr: "localhost:8082"
grpc:
  name: "blog"
  addr: "localhost:8883"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "localhost:2379"
zap:
  DebugFileName: "C:\\Users\\Libra\\Desktop\\libra_go\\logs\\project-debug.log"
  InfoFileName:  "C:\\Users\\Libra\\Desktop\\libra_go\\logs\\project-info.log"
  WarnFileName:  "C:\\Users\\Libra\\Desktop\\libra_go\\logs\\project-error.log"
  MaxSize:       500
  MaxAge:        28
  MaxBackups:    3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
mysql:
  username: root
  password: root
  host: localhost
  port: 3309
  db: libra
jwt:
  accessExp: 7
  refreshExp: 30
  accessSecret: libra
  refreshSecret: libra
aliyunoss:
  bucketName: libra-blog
  endpoint: oss-cn-beijing.aliyuncs.com
  roleArn: acs:ram::1297456591392749:role/ramoss
  regin: cn-beijing
  id: LTAI5tB75QwZq1LS3yXJJPk7
  secret: qW1bQq8cTFC2J7ZGLuOKNJfnWU6EfJ