server:
  name: "api"
  addr: "localhost:80"
etcd:
  addrs:
    - "localhost:2379"
zap:
  DebugFileName: "C:\\Users\\Libra\\Desktop\\libra_go\\logs\\project-debug.log"
  InfoFileName:  "C:\\Users\\Libra\\Desktop\\libra_go\\logs\\project-info.log"
  WarnFileName:  "C:\\Users\\Libra\\Desktop\\libra_go\\logs\\project-error.log"
  MaxSize:       500
  MaxAge:        28
  MaxBackups:    3